import Head from 'next/head';
import { useRouter } from 'next/router';
import { useEffect } from 'react';
import Loading from '../components/loading';

export default function Home() {
  const router = useRouter();
  useEffect(() => {
    router.push('/posts');
  }, [router]);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Loading />
    </div>
  );
}
